# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-28 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articledetail',
            name='article',
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=32, verbose_name='文章标题'),
        ),
        migrations.DeleteModel(
            name='ArticleDetail',
        ),
    ]
