# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-10 01:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180228_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleDetail',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.Article')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=32, verbose_name='分类标题'),
        ),
    ]
